### ISSUE TITLE
smart variable detection

### ISSUE THREAD

**Issue by WebCloud** [nicooprat/Css2Less#1]
One good feature that could be added to this project is identify repetitive declarations and use them as variables.

**Comment by nicooprat** [comment]
Good point ! It's on the todo :) If you're good at Ruby you're welcome to add this feature here https://github.com/thomaspierson/libcss2less

**Comment by allybee** [comment]
I was thinking this as well. Also, mixins for multi-prefix properties like box-shadow and border-radius.

**Comment by nicooprat** [comment]
This feature has been reported there :

https://github.com/thomaspierson/libcss2less/issues

Thanks everybody.
