### ISSUE TITLE
Direct child bug

### ISSUE THREAD

**Issue by petsagouris** [nicooprat/Css2Less#2]
css2less has been on reddit, on that thread the following bug was discovered:

```
.foo > .blah {
    background: red;
}
```

 ... produces ...

```
.foo {
    > {
        .blah {
            background: red;
        }
    }
}
```

That is not valid LESS...must be a bug. It should read something like this:

```
.foo {
     & > .blah {
         background: red;
     }
  }
```

[source comment](http://www.reddit.com/r/webdev/comments/t5j6y/css_to_less/c4jv1l2)

**Comment by nicooprat** [comment]
You're right, I already filled it on the library repository : https://github.com/thomaspierson/libcss2less/issues

Thanks anyway, and feel free to add news bugs and feature requests there :)
