### ISSUE TITLE
Comments not handled well

### ISSUE THREAD

**Issue by stevenmc** [nicooprat/Css2Less#3]
My CSS file had comments in such as this:

```
/*
*   Template
*   -------------------------
*/
```

They created significant problems with incorrect LESS syntax being generated.

**Comment by stevenmc** [comment]
Incorrectly parses @import 'reset.css'; command.

**Comment by stevenmc** [comment]
Feature suggestion: parse colours, and if multiple instances of the same colour are found, turn these into variables, and declare them at the start of the file.

**Comment by nicooprat** [comment]
Many thanks for your bug reports. I transfered them on the library repository because it's about the compiler work and not the webapp's. 

( NB : in the future be sure to create one issue for each issue / feature request. )
